/// UserDefaults keys. Existing installs store these names on disk, so they never change. JotSettings defines which of them are user settings.
public enum JotDefaultsKey {
    public static let cleanUpDictation = "cleanUpDictation"
    public static let cleanUpTranscriptions = "cleanUpTranscriptions"
    public static let fnRequested = "fnRequested"
    public static let highlightTargetField = "highlightTargetField"
    public static let muteSpeakersDuringDictation = "muteSpeakersDuringDictation"
    public static let keepMacAwakeWhileListening = "keepMacAwakeWhileListening"
    public static let keepAudioForSpeakerPass = "keepAudioForSpeakerPass"
    public static let newSessionAfterSilence = "newSessionAfterSilence"
    public static let automaticMicrophone = "automaticMicrophone"
    public static let updateMeetingTitle = "updateMeetingTitle"
    public static let selectedInputUID = "selectedInputUID"
    public static let selectedInputName = "selectedInputName"
    public static let transcriptionTuning = "transcriptionTuning"
    public static let modelUpdateChecks = "modelUpdateChecks"
    public static let modelsPrepared = "modelsPrepared"
    public static let servicePaused = "servicePaused"
    public static let historyTextView = "historyTextView"
    public static let suggestionShortcut = "suggestionShortcut"
    public static let suggestionsEnabled = "suggestionsEnabled"
    public static let suggestionScreenContext = "suggestionScreenContext"
    public static let suggestionHeardMatches = "suggestionHeardMatches"
    public static let suggestionWindowMinutes = "suggestionWindowMinutes"
    public static let dictationShortcut = "dictationShortcut"
    public static let personalVocabulary = "personalVocabulary"
    public static let setupStatus = "setupStatus"
    public static let setupStep = "setupStep"
}
